---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ggpro

<!-- badges: start -->
<!-- badges: end -->

The goal of ggpro is to ...

## Installation

You can install the development version of ggpro from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("EvaMaeRey/ggpro")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r}
library(tidyverse)


```

```{r example}
# library(ggpro)
## basic example code



scale_x_vbar <- function(drop = F, wrap = 15, labels = function(x){stringr::str_wrap(x, wrap)}, ...){
  
    scale_x_discrete(drop = drop, 
                     labels = labels)
  
}    

  
scale_y_vbar <- function(expand = expansion(c(0, .1)), yaxis_title = "", labels = function(x){ifelse(x == max(x, na.rm = T), paste0("\n", x, "\n", yaxis_title), x)}, ...){
 
  scale_y_continuous(expand = expand, labels = labels, ...)
   
}


theme_vbar <- function(){
  
  theme(axis.line.x = element_blank(),
             panel.grid.major.x = element_blank(),
             panel.grid.minor.x = element_blank(),
             panel.grid.minor.y = element_blank(),
             panel.grid.major.y = element_line(),
             axis.title = element_blank(),
             axis.ticks = element_blank(),
             axis.line.x.bottom = element_line())
  
}


geom_vbar <- function(yaxis = T, wrap = 15, yaxis_title = "", ...){
  
  list(geom_bar(...),
       theme_vbar(),
       scale_x_vbar(wrap = wrap),
       scale_y_vbar(yaxis_title = yaxis_title),
       NULL
       )
  
}

geom_vbar_label <- function(...){
  
  
  statexpress::qlayer(geom = statexpress::qproto_update(GeomLabel,
                                                        aes(vjust = 0, linewidth = 0, fill = NA)),
                      stat = statexpress::qproto_update(StatCount, aes(label = after_stat(count)))
                                                )
  
}




```


```{r}
diamonds |> 
  ggplot() + 
  aes(x = cut) + 
  geom_vbar() + 
  geom_vbar_label()

ggchalkboard:::theme_blackboard() |> theme_set()

last_plot()

last_plot() + 
  scale_y_vbar(yaxis_title = "diamonds", limits = c(0, nrow(diamonds)))

last_plot() + 
  scale_x_vbar(wrap = 6)


```


